/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_appsync_graphqlEndpoint:
    "https://lwgp27rjrbbkzkodsojactnhum.appsync-api.us-east-2.amazonaws.com/graphql",
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-lfwuz6qrwnho5fcyprxhd5i2vm",
  aws_cognito_identity_pool_id:
    "us-east-2:aaa9c88b-9445-404a-88c5-f05a75bd9ede",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_dEsE3CsTo",
  aws_user_pools_web_client_id: "3vocp2icaji2608be3otl25s50",
  oauth: {},
  aws_cognito_login_mechanisms: ["EMAIL"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      "REQUIRES_LOWERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_SYMBOLS",
      "REQUIRES_UPPERCASE"
    ]
  },
  aws_cognito_verification_mechanisms: ["EMAIL"]
};

export default awsmobile;
